Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  resources :users, only: [:index, :show]
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy, :index]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

Project/app/models/post.rb
class Post < ApplicationRecord
   belongs_to :user
   has_many :comments ,dependent: :destroy
   validates :title, presence: true, length: { minimum: 3 }
   validates :body, presence: true, length: { maximum: 140 , minimum: 2 }
end

Project/app/models/relationship.rb
class Relationship < ApplicationRecord
 
    belongs_to :invited_user, class_name: 'User', foreign_key: :invited_id
    belongs_to :inviting_user, class_name: 'User', foreign_key: :inviting_id
end

Project/app/models/user.rb
class User < ApplicationRecord
	
  has_many :posts, dependent: :destroy
  has_many :comments ,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	
  def full_name
      name.blank? ? email : name
  end

  has_many :sent_invites, class_name: "Relationship", foreign_key: :inviting_id
  has_many :received_invites, class_name: "Relationship", foreign_key: :invited_id

  has_many :invited_users, through: :sent_invites, source: :invited_user
  has_many :inviting_users, through: :received_invites, source: :inviting_user

end

Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

Project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post =Post.find(params[:post_id])
    @comment= @post.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post
    else
      flash.now[:danger] = "error"
    end
   
  end
end

Project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
   # @posts = Post.all
    @posts = Post.order('created_at DESC').page(params[:page]).per(15)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(allowed_params)

    if @post.save
      flash[:success] = "Created new post"
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    redirect_to posts_path unless @post.user == current_user
  end

  def update
    if @post.user == current_user
      if @post.update_attributes(allowed_params)
        flash[:success] = "Updated post"
        redirect_to @post
      else
        render 'edit'
      end
    else
      redirect_to posts_path
      flash[:notice] = "You can't do this"
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to posts_path
      flash[:success] = "deleted post"
    else
      redirect_to root_path
      flash[:danger] = "You can't do this"
    end
  end

  private
    def allowed_params
      params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find(params[:id])
    end
end

Project/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 before_action :authenticate_user!
  def create
    @invited_user = User.find(params[:relationship][:invited_id])
    if @invited_user.id != current_user.id
      @relationship = current_user.sent_invites.build(invited_id: @invited_user.id)

      if @relationship.save
          flash[:success] = "Successfully invited"
          redirect_to @invited_user
      else
          flash[:danger] = "Unsuccessful"
          redirect_to
      end
    else
      flash[:success] = "you cant follow yourself"
      redirect_to @invited_user
    end
  end

  
 
  def destroy
    @relationship = Relationship.find(params[:id])
    if @relationship.inviting_user == current_user
      @relationship.destroy
      flash[:success] = "Removed relationship"
    end
    redirect_to @relationship.invited_user
  end

  
 
  def index
    @sent_invites = current_user.sent_invites
    @received_invites = current_user.received_invites
  end



end

Project/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home
   end
end

Project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.page(params[:page]).per(30)
  end

  def show
    @user = User.find(params[:id])
  end
end

Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Project/app/helpers/comments_helper.rb
module CommentsHelper
end

Project/app/helpers/posts_helper.rb
module PostsHelper
end

Project/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Project/app/helpers/users_helper.rb
module UsersHelper
end

Project/app/views/comments/_comment.html.erb
<p>
<small><strong>By: </strong><%= comment.user.email %></small><br>
<%= comment.body%><br>
<%= time_ago_in_words(comment.created_at)%>
</p>

Project/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
  <p> <%= f.label :body %> 
      <%= f.text_area :body%> 
   </p>
    <br>
  <p><%= f.submit %></p>
<% end %>

Project/app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>


<script>
    $('.alert').fadeOut(4000);
</script>

Project/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Tweet page", root_path, class: 'navbar-brand' %>
        </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Members', users_path %></li>
        <% if current_user %>
            <li><%= link_to 'Posts', posts_path %></li>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>

            <li><%= link_to 'Tweets',relationships_path %></li>

            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
    </ul>
   </div>

    </div>
</nav>

Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
   <%= render 'layouts/flash_messages' %>
  <%= render 'layouts/menu' %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

Project/app/views/posts/edit.html.erb
<h1 align="center" style="color:red">Edit post<h1>
<p><%= link_to 'back', post_path(@post) %></p>

<%= form_for @post do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
            <%= f.label :title, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :body, class: 'control-label' %>
            <%= f.text_area :body, class: 'form-control', rows: 6 %>
        </div>

        <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<br />
<p><%= link_to 'delete post', @post, method: :delete, data: {confirm: "Are you sure you want to delete this permanently?"} %></p>
 

Project/app/views/posts/index.html.erb
<h1>This will be a list of posts</h1>
<%= link_to 'New Post', new_post_path %>
<ul>
 <% relations=[] %>
   <%  current_user.sent_invites.each do |f| %>
     <% relations << f.invited_user.email %>
   <%end%>
    <%  current_user.received_invites.each do |f| %>
     <% relations << f.invited_user.email %>
   <%end%>
   <% relations << current_user.email%>
    <% @posts.each do |p| %>
       <% if relations.include?p.user.email %>
        <li>
            <h3><%= link_to p.title, post_path(p.id) %></h3>
            <p><small><strong>By: </strong><%= p.user.email %></small></p>
            <p><%= p.body %></p>
         </li>
       <% end %>
     <% end %>
 
</ul>

Project/app/views/posts/new.html.erb
<%= form_for @post do |f| %>
     <%= render 'shared/error_messages', object: f.object %>
     <div class="form-group">
         <%= f.label :title, class: 'control-label' %>
         <%= f.text_field :title, class: 'form-control' %>
     </div>

     <div class="form-group">
         <%= f.label :body, class: 'control-label' %>
         <%= f.text_area :body, class: 'form-control', rows: 6 %>
     </div>

     <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

Project/app/views/posts/show.html.erb
  <h1>
  <%= @post.title %>
  <% if @post.user == current_user %>
    <small><%= link_to 'edit', edit_post_path(@post) %></small>
  <% end %>
  </h1>
  <p><small><strong>By: </strong><%= @post.user.email %></small></p>
  <p><%= @post.body %></p>
  <br>
   <h3><%= @post.comments.count%> Comments</h3>
  
   <%= render @post.comments%>
   <h3>Add comments</h3>
   <%= render 'comments/form'%>
  <br>

Project/app/views/relationships/index.html.erb
<% if @sent_invites.any? %>
    <h3>Following</h3>
  <!--  <%= @sent_invites %> -->
    <ul>
      <% @sent_invites.each do |invitation| %>
          <li><%= link_to invitation.invited_user.full_name, user_path(invitation.invited_user) %></li>
      <% end %>
    </ul>
   <!-- <%= @sent_invites %>  -->
<% end %>

<% if @received_invites.any? %>
    <h3>Followers</h3>
  <!--  <%= @received_invites %> -->
    <ul>
      <% @received_invites.each do |invitation| %>
          <li><%= link_to invitation.invited_user.full_name, user_path(invitation.invited_user) %></li>
      <% end %>
    </ul>
   <!-- <%= @received_invites %> -->
<% end %>

Project/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

Project/app/views/static_pages/home.html.erb
<h1 align="center"  style="color:red">Twitter</h1>

Project/app/views/users/index.html.erb
<div class="container">
    <div class="users row">
        <%= paginate(@users) %>
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                
                <p><%= user.full_name %></p>
            </div>
            <% end %>
        </div>
        <% end %>
        <%= paginate(@users) %>
    </div>
</div>
 

Project/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

Project/app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-4 col-md-3">
        <h1><%= @user.full_name %></h1>       
	
     
	<% if current_user %>
	  <% @relationship = current_user.sent_invites.where(invited_id: @user.id).first %>

	  <% if @relationship %>
	    <%= link_to "Stop following", @relationship, method: :delete %>
	  <% else %>
	    <%= form_for :relationship, url: relationships_path, html: { method: :post } do |f| %>
	      <%= f.hidden_field :invited_id, value: @user.id %>
	      <%= f.submit 'Follow', class: 'btn btn-primary' %>
	    <% end %>
	  <% end %>
	<% end %>
        <ul>
            <%= content_tag(:li, ("Name: " + @user.name)) unless @user.name.blank? %>
            <%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " old")) unless @user.date_of_birth.blank? %>
        </ul>
    </div>
</div>